#!/usr/bin/env python
""" Run the tests as fast as possible """

import os
import sys
import cpuinfo

numcpu = cpuinfo.get_cpu_info()["count"] + 1

os.chdir(os.path.normpath(os.path.join(os.path.abspath(__file__), os.pardir)))

coverage = "--no-cov-on-fail --cov-report term-missing --cov ."
targets = "tests/*.py dominion/*.py dominion/*/*.py dominion/*/*/*.py"
cmd = f"pytest -n {numcpu} {coverage} {targets}"
print(f"{cmd=}")
rc = os.system(cmd)
os.system("coverage html")

# Now try running example games
if not rc:
    for cardset in os.listdir("cardset"):
        cs_str = f"cardset/{cardset}"
        players = "--randobot 4 --numplayers 4"
        print(f"Playing with {cs_str}")
        grc = os.system(
            f"PYTHONPATH=. ./dominion/rungame.py --oldcards {players} --cardset {cs_str}"
        )
        if grc:
            break

sys.exit(rc >> 8)

# EOF
