#!/usr/bin/env python
""" Run randobot tests """

import os
import sys
import random

os.chdir(os.path.normpath(os.path.join(os.path.abspath(__file__), os.pardir)))

# Now try running example games
cardsets = os.listdir("cardset")
random.shuffle(cardsets)
for cardset in cardsets:
    cs_str = f"cardset/{cardset}"
    if not os.path.isfile(cs_str):
        continue
    cardset_args = f"--cardset {cs_str}"
    players = "--randobot 4 --numplayers 4"
    output_file = f"/tmp/randobot_{cardset}.{os.getpid()}"
    redirect_args = f"> {output_file} 2>&1"
    print(f"Playing with {cs_str}")
    grc = os.system(f"PYTHONPATH=. ./dominion/rungame.py --oldcards {players} {cardset_args} {redirect_args}")
    if grc:
        print(f"Broke playing with {cs_str}")
    else:
        os.unlink(output_file)

sys.exit(grc >> 8)

# EOF
