#!/usr/bin/env python
""" Run randobot tests - play a game very randomly to see what errors pop up"""

import os
import sys

os.chdir(os.path.normpath(os.path.join(os.path.abspath(__file__), os.pardir)))

# Now try running example games
if len(sys.argv) > 1:
    cardsets = sys.argv[1:]
else:
    cardsets = os.listdir("cardset")
grc = 0
for cardset in cardsets:
    cs_str = f"cardset/{cardset}"
    if not os.path.isfile(cs_str):
        continue
    cardset_args = f"--cardset {cs_str}"
    players = "--randobot 4 --numplayers 4"
    output_file = f"/tmp/randobot_{cardset}.{os.getpid()}"
    redirect_args = f"> {output_file} 2>&1"
    env_args = "PYDOMINION_DEBUG=1 PYTHONPATH=."
    print(f"Playing with {cs_str}")
    grc = os.system(
        f"{env_args} ./dominion/rungame.py --oldcards {players} {cardset_args} {redirect_args}"
    )
    if grc:
        print(f"Broke playing with {cs_str}")
    else:
        os.unlink(output_file)

sys.exit(grc >> 8)

# EOF
