#!/usr/bin/env python

import os
import sys
import cpuinfo

numcpu = cpuinfo.get_cpu_info()['count'] + 1

os.chdir(os.path.normpath(os.path.join(os.path.abspath(__file__), os.pardir)))

card_types = ['tests', 'cards', 'events', 'landmarks', 'boons', 'hexes', 'states', 'artifacts', 'projects', 'ways']
checks = ['{}/*.py'.format(_) for _ in card_types]

cmd = 'py.test -n {} --cov-report term-missing --cov . *.py {}'.format(numcpu, " ".join(checks))
rc = os.system(cmd)
sys.exit(rc >> 8)

# EOF
