---
name: run_tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: python3 -m pip install -r requirements-dev.txt
      - name: Run Tests
        run: ./run_tests
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
